### ISSUE TITLE
Suggestion for additions

### ISSUE THREAD

**Issue by BernhardClemm** [henry-yeh/Awesome-LLM-in-Social-Science#1]
This repository is a very valuable ressource, thank you! The following studies may fit your list:

- https://journals.sagepub.com/doi/10.1177/20531680241236239 (my work)
- https://journals.sagepub.com/doi/pdf/10.1177/00811750211053370

**Comment by henry-yeh** [comment]
Thank you for your kind words and suggestions! I will add them ASAP. Welcome to submit PR anytime when you have suggestions.
